/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void changeArea(GCustomSlider source, GEvent event) { //_CODE_:Area:694019:
  println("Area: "+Area.getValueF());
} //_CODE_:Area:694019:

public void changeVelocity(GCustomSlider source, GEvent event) { //_CODE_:Velocidad:909661:
  println("Velocidad: "+Velocidad.getValueF());
} //_CODE_:Velocidad:909661:

public void changeHeight(GCustomSlider source, GEvent event) { //_CODE_:Altura_1:251442:
  println("Altura: "+Altura_1.getValueF());
} //_CODE_:Altura_1:251442:

public void ChangePressure(GCustomSlider source, GEvent event) { //_CODE_:Presion:925886:
  println("Presión: "+Presion.getValueF());
} //_CODE_:Presion:925886:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:970517:
  newWindow = GWindow.getWindow(this, "Nueva Ventana", 100, 100, 1280, 720, JAVA2D);
  newWindow.addDrawHandler(this, "newWindowDraw");
  bg2 = loadImage("bg2.png");

} //_CODE_:button1:970517:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:Altura_2:571161:
   println("Altura: "+Altura_2.getValueF());
} //_CODE_:Altura_2:571161:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Area = new GCustomSlider(this, 935, 125, 300, 60, "grey_blue");
  Area.setShowValue(true);
  Area.setShowLimits(true);
  Area.setLimits(0.005, 5.0E-4, 0.005);
  Area.setShowTicks(true);
  Area.setNumberFormat(G4P.DECIMAL, 4);
  Area.setOpaque(true);
  Area.addEventHandler(this, "changeArea");
  Velocidad = new GCustomSlider(this, 935, 271, 300, 60, "grey_blue");
  Velocidad.setShowValue(true);
  Velocidad.setShowLimits(true);
  Velocidad.setLimits(1.0, 0.5, 8.0);
  Velocidad.setShowTicks(true);
  Velocidad.setNumberFormat(G4P.DECIMAL, 4);
  Velocidad.setOpaque(true);
  Velocidad.addEventHandler(this, "changeVelocity");
  Altura_1 = new GCustomSlider(this, 935, 525, 300, 60, "grey_blue");
  Altura_1.setShowValue(true);
  Altura_1.setShowLimits(true);
  Altura_1.setLimits(1.0, 0.5, 10.0);
  Altura_1.setShowTicks(true);
  Altura_1.setNumberFormat(G4P.DECIMAL, 4);
  Altura_1.setOpaque(true);
  Altura_1.addEventHandler(this, "changeHeight");
  Presion = new GCustomSlider(this, 935, 419, 300, 60, "grey_blue");
  Presion.setShowValue(true);
  Presion.setShowLimits(true);
  Presion.setLimits(200000.0, 200000.0, 1000000.0);
  Presion.setShowTicks(true);
  Presion.setNumberFormat(G4P.DECIMAL, 2);
  Presion.setOpaque(true);
  Presion.addEventHandler(this, "ChangePressure");
  button1 = new GButton(this, 626, 607, 283, 46);
  button1.setText("Mayor Informacion");
  button1.addEventHandler(this, "button1_click1");
  Altura_2 = new GCustomSlider(this, 935, 633, 300, 60, "grey_blue");
  Altura_2.setShowValue(true);
  Altura_2.setShowLimits(true);
  Altura_2.setLimits(0.5, 0.5, 10.0);
  Altura_2.setShowTicks(true);
  Altura_2.setNumberFormat(G4P.DECIMAL, 2);
  Altura_2.setOpaque(true);
  Altura_2.addEventHandler(this, "custom_slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider Area; 
GCustomSlider Velocidad; 
GCustomSlider Altura_1; 
GCustomSlider Presion; 
GButton button1; 
GCustomSlider Altura_2; 
